### ISSUE TITLE
Doesn't work on Win 7 cmd.

### ISSUE THREAD

**Issue by dofine** [timofurrer/colorful#1]
The example doesn't work in Win 7 cmd, it would print all the control codes out. But:
1. It works in [cmder \| Console Emulator](http://cmder.net/)
2. `colorama` works in both cmd and cmder.

**Comment by timofurrer** [comment]
Thanks for the report! I've missed the `colorama.init()`. 

Can you give **v0.3.5** a shot?
Unfortunately, I don't have any Windows computer around to test, so I'd appreciate if you can have a look real quick :beers:

**Comment by Agnewee** [comment]
It's ok on win10.

**Comment by timofurrer** [comment]
Thanks @Agnewee for double checking. 
@dofine can you confirm, please?

**Comment by timofurrer** [comment]
@dofine please respond in this ticket if it still does not work for you.

**Comment by dofine** [comment]
@timofurrer sorry for the late reply. But it's working now. Thanks sooo much!

**Comment by timofurrer** [comment]
Great! Thanks for the confirmation :tada:
