### ISSUE TITLE
Please provide type stubs!

### ISSUE THREAD

**Issue by devxpy** [timofurrer/colorful#13]
Hello, 
thanks for this wonderful module!

Can we please have type stubs (`.pyi` files), to enable code-completion in IDEs?

**Comment by timofurrer** [comment]
You're very welcome!

Good point! I'll have a look at those!

**Comment by devxpy** [comment]
Apparently, this is physically impossible. 

The package has a total of `12851374070580` possible enumerations of methods available. Even if we wrote a script that automatically generated a script to build type stubs, this would be too large for anyone to parse xD

**Comment by devxpy** [comment]
Wait, maybe we can have at least a subset of the API that's commonly used.

**Comment by timofurrer** [comment]
Yes, that's right - big number 😄 

> Wait, maybe we can have at least a subset of the API that's commonly used.

Which API did you have in mind? "common" like the "common" colors people might use?

**Comment by devxpy** [comment]
Yes common colors and modifiers..

**Comment by bmoeskau** [comment]
A simple templated file would be useful. I use a dozen or so color combos, and I would be happy to add type definitions manually to make PyCharm happy if I knew the proper location and format to use. Thanks for the useful library!
