### ISSUE TITLE
No color in terminal

### ISSUE THREAD

**Issue by edouard-lopez** [timofurrer/colorful#21]
Hello, 
Thanks for the lib, look promising for my project.

### Actual
When invoking the script with Python (above) I got the correct output, same when invoking `fish_prompt` manually (middle). However, when it's automatically invoked by `fish` there is no color (below).

![dev_231](https://user-images.githubusercontent.com/1212392/53250415-a31e4e00-36ba-11e9-8745-85bc10a5e35b.png)

### Python

```python
import colorful


def prompt(last_command_status=0):
    print(colorful.red('red'))
    symbol = '❯'
    return symbol


if __name__ == "__main__":
    print("%s " % (prompt()))
```

### Fish
Above code is invoked through a snippet in _~/.config/fish/functions/fish_prompt.fish_:

```fish
function fish_prompt
    python3 ~/projects/purish/pure/prompt.py $status
end
```

### Question

Am I missing something here?

**Comment by timofurrer** [comment]
Can you please run:

```python
import os
import colorful

print(colorful.terminal.detect_color_support(os.environ))
```

And post the output here?

**Comment by timofurrer** [comment]
And also try to manually setup the `colormode` like that:

```python
colorful.setup(colormode=colorful.ANSI_256_COLORS)
```

**Comment by edouard-lopez** [comment]
### `colorful.ANSI_256_COLORS` :heavy_check_mark: 
 
Forcing `colorful.ANSI_256_COLORS` add colors

    colorful.setup(colormode=colorful.ANSI_256_COLORS)
    print(colorful.red('last_command_status'), last_command_status)

### `detect_color_support()`

    print("[%s]" % colorful.terminal.detect_color_support(os.environ))

Output 

    [0]

Do you need informatoin to fix `detect_color_support()`?

**Comment by timofurrer** [comment]
Yes, please.

Can you give me the output of:

```python
import sys
print(sys.stdout.isatty())
```

... without that fish environment?

If that output is `False` your script within the fish environment is probably piped and therefore colorful removes coloring.

Definitely have a look at: https://github.com/timofurrer/colorful#color-modes
You could use the `colorful.use_*` methods or environment variable to force the color mode you want.

**Comment by edouard-lopez** [comment]
When calling manually from the terminal
```shell
$ python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.stdout.isatty())
True
>>> 
```

I got `True` both in `bash` and `fish` shell.

However when calling from [my script](https://github.com/edouard-lopez/pure/blob/51362b927fb1752ced243c98b2394b3e425561af/pure/prompt.py#L8-L9) it's `False`.
