### ISSUE TITLE
Support for elvish shell

### ISSUE THREAD

**Issue by edouard-lopez** [timofurrer/colorful#26]
**related:** elves/elvish#804

---

When running in a docker I get ANSI colour code instead of the color should get thanks to [`colorful` module](https://github.com/timofurrer/colorful).

```
❯ docker run \
     --name run-pure-on-elvish \
     --rm \
     --interactive \
     --tty \
     --volume=$PWD:/home/nemo/.pure/ \
     pure-on-elvish-latest
^[[38;2;173;216;230m/home/pure/.pure^[[39m^[[26m
^[[38;2;190;190;190mmaster^[[39m^[[26m^[[38;2;190;190;190m*^[[39m^[[26m
^[[38;2;205;0;0m❯^[[39m^[[26m
```

However if in said container I run a Python3 prompt, it works fine:

```
$ python3
Python 3.6.8 (default, Jan 24 2019, 16:36:30)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import colorful
>>> print(colorful.red('red {0} red'.format(colorful.white('white'))))
red white red  <---------------- colored adequatly
```

I tried to force color in my container using `-e TERM=xterm-256color` without success.

**Comment by timofurrer** [comment]
I'm not really sure how `elvish` shows colors.
The following `Dockerfile` works fine for me:

```dockerfile
FROM ubuntu:18.10

RUN apt update && apt install --yes python3-pip
RUN python3 -m pip install colorful

CMD python3 -c 'import colorful; print(colorful.red("Hello"))'
```

It seems like the color codes are not interpreted by the shell.

The only case where colorful doesn't display colors is if it's being piped. However, if that would be the case you won't see any color codes.

**Comment by edouard-lopez** [comment]
It was a problem with the way I configured `elvish` prompt. I got color with the solution from elves/elvish#804 (redirecting to `/dev/tty`):

    edit:prompt = { python3 $E:PURE_EXECUTABLE_PATH/pure/prompt.py >/dev/tty }
