### ISSUE TITLE
Does not work under windows 10 CMD, POWERSHELL or CONEMU

### ISSUE THREAD

**Issue by bradphelan** [timofurrer/colorful#27]
from basic cmd.exe shell

![image](https://user-images.githubusercontent.com/17650/56563368-c62a8880-65ab-11e9-8420-01d00b44f619.png)

from conemu shell

![image](https://user-images.githubusercontent.com/17650/56563393-d93d5880-65ab-11e9-8073-ce98fd55f83b.png)

from powershell shell

![image](https://user-images.githubusercontent.com/17650/56563422-eeb28280-65ab-11e9-9fe8-80715d6b5162.png)

According to conemu setup I have 24 bit support

![image](https://user-images.githubusercontent.com/17650/56563709-af386600-65ac-11e9-866f-1f061dae19d4.png)

**Comment by timofurrer** [comment]
Thanks for reporting!

A few things:

1. Can you please provide the output of: `platform.system()`. colorful uses colorama to support windows - let's see if that got enabled correctly.
2. Can you please run the following and provide the output:
```python
import os
import colorful

print(colorful.terminal.detect_color_support(os.environ))
```

**Comment by timofurrer** [comment]
Anything?

**Comment by timofurrer** [comment]
Pretty stale, I'll re-open if more information is provided. Thanks 🎉
