### ISSUE TITLE
COLORNAMES_COLORS does not exist

### ISSUE THREAD

**Issue by mhucka** [timofurrer/colorful#31]
In the README section titled [Color palette](https://github.com/timofurrer/colorful#color-palette), there is this example:

```
colorful.setup(colorpalette=colorful.COLORNAMES_COLORS))
```

Aside from the extra `)` at the end of the line, the statement above produces an error: _"the color "COLORNAMES" is unknown. Use a color in your color palette (by default: X11 rgb.txt)"_.  Searching the code reveals that there is no symbol `COLORNAMES_COLOR` anywhere (except in the README.md text).

**Comment by timofurrer** [comment]
I've just released [v0.5.2](https://pypi.org/project/colorful/0.5.2/) to PyPI which exposes the `colorful.COLORNAMES_COLORS` variable!

Thanks for the issue :tada:
