### ISSUE TITLE
INFO: Drop Python 2.7 and Python 3.4 support

### ISSUE THREAD

**Issue by timofurrer** [timofurrer/colorful#34]
Support for Python 2.7 will end with the beginning of 2020.
Python 3.4 has gotten it's last update a few months ago in March 2019.

I'll plan to drop Python 2.7 and Python 3.4 support sometime after September 2019.
However, I'm happy to accept PRs for a Python 2.7 and Python 3.4 maintenance branch that I could release accordingly.

**Comment by fliiiix** [comment]
not done yet :sweat_smile:
