### ISSUE TITLE
"crimson" as an X11 color is missing from the default color palette

### ISSUE THREAD

**Issue by notaduck448** [timofurrer/colorful#44]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/timofurrer/colorful/blob/master/.github/CONTRIBUTING.md

[X] I have read and respect the code of conduct at https://github.com/timofurrer/colorful/blob/master/.github/CODE_OF_CONDUCT.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
The color "crimson" is missing from the default color palette. It's a color named on the X11 color list, but is not actually included in this library.

**Environment and Version**
* OS (incl. terminal and shell used): Windows Terminal (Powershell)
* Python Version: 3.8.3
* colorful Version: 0.5.4

**To Reproduce**
```py
import colorful as cf
print(cf.crimson("test"))
```

**Expected behavior**
The text to be printed to the terminal in the appropriate color.

**Comment by fliiiix** [comment]
was that fixed or did you close it because you don't care anymore?
